export const s = {
  container: {
    padding: '2rem',
    height: 'calc(100vh - 100px)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  periodRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '1.5rem',
    alignItems: 'center',
  },
  pill: (active) => ({
    padding: '6px 16px',
    borderRadius: '20px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: '600',
    background: active ? '#F87171' : '#1E2530',
    color: active ? '#0B0F17' : '#6B7280',
    transition: 'all 0.2s',
  }),
  grid: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr',
    gap: '2rem',
    flex: 1,
    minHeight: 0,
  },

  // Левая карточка — итоговая сумма расходов
  mainCard: {
    background: '#7C2D12',
    borderRadius: '24px',
    padding: '2.5rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
  },
  mainCardTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: 'rgba(255,255,255,0.7)',
    marginBottom: '0.5rem',
  },
  mainLabel: {
    fontSize: '0.9rem',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    fontWeight: '600',
  },
  mainAmountRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
    marginBottom: '1.5rem',
  },
  amountNum: {
    fontSize: '5rem',
    fontWeight: '800',
    lineHeight: 1,
    color: '#fff',
  },
  amountEur: {
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#fff',
  },
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(255,255,255,0.15)',
    padding: '6px 12px',
    borderRadius: '8px',
    fontSize: '0.85rem',
    fontWeight: '700',
    alignSelf: 'flex-start',
    color: '#fff',
  },
  badgeSub: { fontWeight: '400', opacity: 0.8, marginLeft: '4px' },
  strip: {
    position: 'absolute',
    bottom: '30px',
    left: '2.5rem',
    right: '2.5rem',
    height: '6px',
    display: 'flex',
    borderRadius: '10px',
    overflow: 'hidden',
    background: 'rgba(255,255,255,0.1)',
  },

  // Правая карточка — разбивка
  breakdownCard: {
    background: '#151B28',
    borderRadius: '24px',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    border: '1px solid rgba(255,255,255,0.05)',
  },
  bdHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  bdTitle: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  bdSub: {
    fontSize: '0.75rem',
    color: '#6B7280',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
    overflowY: 'auto',
    paddingRight: '4px',
  },
  catCard: {
    background: 'rgba(255,255,255,0.03)',
    padding: '14px 18px',
    borderRadius: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  catLeft: { display: 'flex', alignItems: 'center', gap: '15px' },
  iconBg: (color) => ({
    width: '36px',
    height: '36px',
    background: `${color}18`,
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  catInfo: { display: 'flex', flexDirection: 'column', gap: '2px' },
  catLabel: { fontSize: '0.95rem', fontWeight: '600', color: '#fff' },
  catAmount: { fontSize: '1rem', fontWeight: '700', color: '#F87171' },
  catProgressBox: {
    width: '100px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '6px',
  },
  progressText: { fontSize: '0.8rem', fontWeight: '700', color: '#fff' },
  barBg: {
    width: '100%',
    height: '4px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '10px',
  },
  barFill: (color, width) => ({
    background: color,
    width: `${Math.min(width, 100)}%`,
    height: '100%',
    borderRadius: '10px',
  }),
  empty: {
    color: '#4A5568',
    fontSize: '0.85rem',
    textAlign: 'center',
    padding: '2rem 0',
  },
};

export const PERIOD_LABELS = { week: 'Неделя', month: 'Месяц', year: 'Год' };

export const CAT_COLORS = [
  '#F87171', '#FB923C', '#FBBF24',
  '#A78BFA', '#60A5FA', '#34D399',
];

export const CAT_LABELS = {
  materials:  'Материалы',
  personnel:  'Персонал',
  rent:       'Аренда',
  insurance:  'Страховка',
  software:   'ПО',
  other:      'Прочее',
  expense:    'Расходы',
};
