export const s = {
  container: {
    padding: '2rem',
    height: 'calc(100vh - 100px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    boxSizing: 'border-box',
  },
  chatWrapper: {
    width: '80%',
    maxWidth: '1000px',
    background: '#151B28',
    borderRadius: '24px',
    border: '1px solid rgba(255,255,255,0.05)',
    display: 'flex',
    flexDirection: 'column',
    height: '90%',
    overflow: 'hidden',
  },
  chatHeader: {
    padding: '1.5rem 2rem',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  botAvatar: {
    width: '48px',
    height: '48px',
    background: 'rgba(0, 229, 255, 0.1)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botName: { margin: 0, color: '#fff', fontSize: '1.2rem', fontWeight: '700' },
  statusRow: { display: 'flex', alignItems: 'center', gap: '6px', marginTop: '4px' },
  statusDot: { width: '6px', height: '6px', background: '#10B981', borderRadius: '50%' },
  statusText: { color: '#6B7280', fontSize: '0.8rem' },
  poweredBadge: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: '12px',
    color: '#00E5FF',
    fontSize: '0.8rem',
    fontWeight: '600',
  },
  messagesArea: {
    flex: 1,
    padding: '2rem',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  botMsgRow: { display: 'flex', gap: '12px', alignSelf: 'flex-start', maxWidth: '80%' },
  userMsgRow: { alignSelf: 'flex-end', maxWidth: '80%' },
  miniAvatar: {
    width: '32px',
    height: '32px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  botBubble: {
    background: 'rgba(255,255,255,0.05)',
    padding: '12px 20px',
    borderRadius: '0 20px 20px 20px',
    color: '#E2E8F0',
    lineHeight: '1.5',
    fontSize: '0.95rem',
  },
  userBubble: {
    background: '#00E5FF',
    color: '#0B0F17',
    padding: '12px 20px',
    borderRadius: '20px 20px 0 20px',
    fontWeight: '500',
  },
  inputContainer: {
    padding: '1.5rem 2rem',
    background: '#151B28',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid rgba(0, 229, 255, 0.2)',
    borderRadius: '16px',
    padding: '16px 60px 16px 20px',
    color: '#fff',
    fontSize: '1rem',
    outline: 'none',
    transition: '0.3s',
  },
  sendBtn: {
    position: 'absolute',
    right: '12px',
    background: 'none',
    border: 'none',
    color: '#6B7280',
    cursor: 'pointer',
    display: 'flex',
  },
  footerNote: {
    textAlign: 'center',
    color: '#4A5568',
    fontSize: '0.75rem',
    marginTop: '12px',
    fontStyle: 'italic',
  }
};