export const PERIOD_LABELS = { week: 'Неделя', month: 'Месяц', year: 'Год' };

export const INCOME_COLORS = ['#2563EB', '#4ADE80', '#A855F7', '#FBBF24', '#F87171', '#34D399', '#60A5FA'];
export const EXPENSE_COLORS = ['#F87171', '#FB923C', '#FBBF24', '#A78BFA', '#60A5FA', '#34D399'];

export const CAT_LABELS = {
  materials: 'Материалы',
  personnel: 'Персонал',
  rent: 'Аренда',
  insurance: 'Страховка',
  software: 'ПО',
  other: 'Прочее',
  expense: 'Расходы',
  income: 'Доходы',
};

export const s = {
  container: {
    padding: '1.5rem 2rem',
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    boxSizing: 'border-box',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
  },
  tabGroup: {
    display: 'flex',
    background: '#151B28',
    borderRadius: '12px',
    padding: '4px',
    gap: '4px',
  },
  tab: (active, color) => ({
    padding: '7px 20px',
    borderRadius: '9px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontWeight: '700',
    background: active ? color : 'transparent',
    color: active ? '#fff' : '#6B7280',
    transition: 'all 0.2s',
  }),
  divider: {
    width: '1px',
    height: '28px',
    background: '#1E2530',
    margin: '0 4px',
  },
  pill: (active) => ({
    padding: '6px 14px',
    borderRadius: '20px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: '600',
    background: active ? '#374151' : '#1E2530',
    color: active ? '#fff' : '#6B7280',
    transition: 'all 0.2s',
  }),
  csvBtn: {
    marginLeft: 'auto',
    background: 'transparent',
    border: '1px solid #1E2530',
    color: '#9CA3AF',
    padding: '6px 14px',
    borderRadius: '10px',
    fontSize: '0.78rem',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr',
    gap: '1.5rem',
    alignItems: 'start',
  },
  mainCard: (bg) => ({
    background: bg,
    borderRadius: '24px',
    padding: '2.5rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    minHeight: '260px',
  }),
  mainCardTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: 'rgba(255,255,255,0.7)',
    marginBottom: '0.5rem',
  },
  mainLabel: {
    fontSize: '0.9rem',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    fontWeight: '600',
  },
  mainAmountRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '10px',
    marginBottom: '1.5rem',
  },
  amountNum: {
    fontSize: '4.5rem',
    fontWeight: '800',
    lineHeight: 1,
    color: '#fff',
  },
  amountEur: {
    fontSize: '2rem',
    fontWeight: '700',
    color: '#fff',
  },
  badge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(255,255,255,0.15)',
    padding: '6px 12px',
    borderRadius: '8px',
    fontSize: '0.85rem',
    fontWeight: '700',
    alignSelf: 'flex-start',
    color: '#fff',
  },
  badgeSub: { fontWeight: '400', opacity: 0.8 },
  strip: {
    position: 'absolute',
    bottom: '24px',
    left: '2.5rem',
    right: '2.5rem',
    height: '6px',
    display: 'flex',
    borderRadius: '10px',
    overflow: 'hidden',
    background: 'rgba(255,255,255,0.1)',
  },
  breakdownCard: {
    background: '#151B28',
    borderRadius: '24px',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid rgba(255,255,255,0.05)',
    minHeight: '280px',
  },
  bdHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.2rem',
  },
  bdTitle: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  bdSub: {
    fontSize: '0.75rem',
    color: '#6B7280',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.7rem',
    overflowY: 'auto',
    maxHeight: '420px',
  },
  catCard: {
    background: 'rgba(255,255,255,0.03)',
    padding: '12px 16px',
    borderRadius: '14px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  catLeft: { display: 'flex', alignItems: 'center', gap: '12px' },
  iconBg: (color) => ({
    width: '34px',
    height: '34px',
    background: `${color}18`,
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.9rem',
  }),
  catInfo: { display: 'flex', flexDirection: 'column', gap: '2px' },
  catLabel: { fontSize: '0.9rem', fontWeight: '600', color: '#fff' },
  catAmount: (color) => ({ fontSize: '0.95rem', fontWeight: '700', color }),
  catProgressBox: {
    width: '90px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '5px',
  },
  progressText: { fontSize: '0.78rem', fontWeight: '700', color: '#fff' },
  barBg: {
    width: '100%',
    height: '4px',
    background: 'rgba(255,255,255,0.05)',
    borderRadius: '10px',
  },
  barFill: (color, width) => ({
    background: color,
    width: `${Math.min(width, 100)}%`,
    height: '100%',
    borderRadius: '10px',
  }),
  empty: {
    color: '#4A5568',
    fontSize: '0.85rem',
    textAlign: 'center',
    padding: '2rem 0',
  },
};
